#!/usr/bin/env bash
# This script displays information about subdomains.

domainInfo() {
    local RESPONSE=$(dig $1 | grep -A1 'ANSWER SECTION:' | awk 'NR==2 {print $0}')
    echo "The subdomain $2 is a $(echo $RESPONSE | awk '{print $4}') record and points to $(echo $RESPONSE | awk '{print $5}')"
}

if [[ $# == 1 ]]; then
    listOfSubdomains=('www' 'lb-01' 'web-01' 'web-02')
    for i in "${listOfSubdomains[@]}";do
        WEBURL="$i.$1"
        domainInfo $WEBURL $i
    done
else
    WEBURL="$2.$1"
    domainInfo $WEBURL $2
fi

