#!/usr/bin/env bash
# A Bash script that configures Nginx server 
# so that /redirect_me is redirecting to another page.
sudo apt-get -y update
sudo apt-get -y install nginx
USER=$(whoami)
sudo chown "$USER":"$USER" /var/www/html/
# Create index.html file with "Hello World!"
echo "Hello World!" | sudo tee /var/www/html/index.html
# use sed to insert the redirect configuration
sed -i '/listen 80 default_server/a rewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;' /etc/nginx/sites-available/default
# Restart nginx
sudo service nginx restart

