#!/usr/bin/env bash
# A Bash script that configures Nginx server 
# so that /redirect_me is redirecting to another page.
sudo apt-get -y update
sudo apt-get -y install nginx
USER=$(whoami)
sudo chown "$USER":"$USER" /var/www/html/
# Create index.html file with "Hello World!"
sudo echo "Hello World!" > /var/www/html/index.html
# use sed to insert the redirect configuration
sed -i '/^\tserver_name.*/a rewrite ^/redirect_me https://www.goalkicker.com/ permanent;' /etc/nginx/sites-available/default
# Restart nginx
sudo /etc/init.d/nginx restart

