#!/usr/bin/env bash
# A Bash script that configures Nginx server 
# so that /redirect_me is redirecting to another page.
sudo apt-get -y update
sudo apt-get -y install nginx
USER=$(whoami)
sudo chown "$USER":"$USER" /var/www/html/
# Create index.html file with "Hello World!"
echo "Hello World!" | sudo tee /var/www/html/index.html
# Create 404.html
echo "Ceci n'est pas une page" | sudo tee /var/www/html/404.html
# use sed to insert that redirect configuration
sudo sed -i '/server {/a \  error_page 404 /404.html;\n location = /404.html {\n internal;\n root /var/www/html; \n} \n}' /etc/nginx/sites-available/default
# Restart nginx
sudo /etc/init.d/nginx restart

