#!/usr/bin/env bash
# install and configure HAproxy on server to serve as load balancer
sudo apt-get install -y software-properties-common
sudo add-apt-repository -y ppa:vbernat/haproxy-1.8
sudo apt-get -y update
sudo apt-get -y install haproxy=1.8.\*
echo -e '
frontend http-in
\tmode http
\tbind *:80
\tdefault_backend web_servers

backend web_servers
\tbalance roundrobin
\tserver web-01 35.190.151.203:80 check
\tserver web-02 54.167.86.179:80 check
' >> /etc/haproxy/haproxy.cfg
echo -e '
ENABLED=1' >> /etc/default/haproxy
service haproxy restart
