#!/usr/bin/env bash
# configures a new HAproxy as a load balancer

# Install HAproxy on a server
sudo apt-get -y update
sudo apt-get -y install haproxy

# Configure haproxy configuration file to distribute requests using a roundrobin algorithm
USER=$(whoami)
sudo chown "$USER":"$USER" /etc/haproxy/haproxy.cfg
echo '
frontend idayisit.tech
        bind *:80
        default_backend web_servers

backend web_servers
        balance roundrobin
        server 530680-web-01 54.237.67.242:80 check
        server 530680-web-02 100.25.0.50:80 check
' >> /etc/haproxy/haproxy.cfg

# Restart HAproxy service
sudo service haproxy restart
