#!/usr/bin/env bash
# install and configure HAproxy on server to serve as load balancer
sudo apt-get install -y software-properties-common
sudo add-apt-repository -y ppa:vbernat/haproxy-1.8
sudo apt-get -y update
sudo apt-get -y install haproxy=1.8.\*
echo -e '
frontend http-in
\tmode http
\tbind *:80
\tdefault_backend web_servers

backend web_servers
\tbalance roundrobin
\tserver 530680-web-01 54.237.67.242:80 check
\tserver 530680-web-02 54.146.66.111:80 check
' >> /etc/haproxy/haproxy.cfg
echo -e '
ENABLED=1' >> /etc/default/haproxy
service haproxy restart
