#!/usr/bin/env bash
# Write a Bash script that generates a MySQL dump and creates a compressed archive out of it.

#Archive Name
archive_name="$(date +'%d-%m-%Y').tar.gz"

# Generate MySQL DUMP
mysqldump --all-databases -u root -p "$1" > backup.sql

tar -czvf "$archive_name" backup.sql