#!/usr/bin/env bash
# write a bash script that prints Best School 10 times
indx=0
while (( indx < 10 )); do
	echo "Best School"
	if (( indx == 3 )); then
		echo "bad luck"
	fi
	if (( indx == 7 )); then
		echo "good luck"
	fi
	((indx++))
done
