#!/usr/bin/env bash
# write a bash script that prints bad luck for the 4th iteration, good luck for the 8th iteration else Best School
indx=0
while (( indx < 10 )); do
	if (( indx == 3 )); then
		echo "bad luck"
	elif (( indx == 7 )); then
		echo "good luck"
	else
		echo "Best School"
	fi
	((indx++))
done
