#!/usr/bin/env bash
# write a bash script that prints bad luck for the 4th iteration, good luck for the 8th iteration else Best School
indx=1
while (( indx < 21 )); do
	echo "$indx"
	case "$indx" in
		4) echo "bad luck from China";;
		9) echo "bad luck from Japan";;
		17) echo "bad luck from Italy";;
	esac
	((indx++))
done
