#!/usr/bin/env bash
# change your ip address and that of facebook.com
grep -vwE "(localhost|facebook.com)" /etc/hosts > ~/hosts.new
echo "127.0.0.2        localhost" >> ~/hosts.new
echo "8.8.8.8        facebook.com" >> ~/hosts.new
cp -f ~/hosts.new /etc/hosts
