#!/usr/bin/env bash
# Write a Script the runs Nginx container as nginx user

# Stop nginx if it's already running
service nginx stop

# Modify nginx configuration
chown nginx:nginx /etc/nginx/nginx.conf
chown nginx:nginx /etc/nginx/sites-available/default
chmod u+rwx /etc/nginx/nginx.conf
chmod u+rwx /etc/nginx/sites-available/default
sed -i 's/user\s*nginx;/user nginx;/' /etc/nginx/nginx.conf
sed -i 's/listen\s*80;/listen 8080;/' /etc/nginx/sites-available/default

# Start nginx
pkill apache2
su nginx service nginx restart